# Generated by Django 3.2.5 on 2021-07-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_id', models.IntegerField()),
                ('deal_name', models.CharField(blank=True, max_length=250, null=True)),
                ('deal_stage', models.CharField(blank=True, max_length=250, null=True)),
                ('close_date', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('deal_type', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
