# Generated by Django 3.2.5 on 2021-07-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='deal_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
