# Generated by Django 3.2.5 on 2021-07-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_deal_deal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('expires_in', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
